version: "3.8"

services: 
  node-app:
    build: ./node-app
    container_name: node-app
    expose: 
        - "3000"
  nginx: 
    image: nginx:alpine
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app


